### PR TITLE
Change min SDK to 7

### PR DESCRIPTION
**Pull request by elevenfive**
It appears to work fine on 7 - is there any reason you set the min to 8 originally?

### CODE REVIEW

**Comment by moxie0** [comment]
No real reason, SDK8 is just my personal minimum on what I'm willing to support at this moment.  The number of devices <8 is so low now that I don't find it to be a problem.  Definitely looking forward to the day when I can raise it to 14 across all my projects. =)

**Comment by elevenfive** [comment]
So, care to merge?

**Comment by elevenfive** [comment]
Hey Moxie - are you concerned that there might be problems lowering the min API?  I'm curious if you think it would be safe to lower it to 7 in an app I'm working on that already has a min api of 7.

**Comment by moxie0** [comment]
Hey @elevenfive, sorry for the slow response.  I don't really want to support a minsdk of 7, although I don't specifically know of any problems that will arise.  I'm basically just doing minsdk of 8 in all my projects now, and don't want to have to deal with anything that could potentially result from a lower minsdk.

Feel free to experiment with lowering the minsdk for your own project, but I'm unlikely to merge this in to master.

**Comment by elevenfive** [comment]
No worries - I'll post the results.  Based on the changelog for API 8 I'd be very surprised if there were any issues.

http://developer.android.com/sdk/api_diff/8/changes.html

**Pull request closed without merging**
